
/*
 * Generated by TPTC - Translate Pascal to C
 *     Version 1.7 03/26/88   (C) 1988 S.H.Smith
 */
#include "tptcmac.h"

/*
 *   Ackerman function
 */ 

 /* program acker  */ 


  integer      r; 

  
integer      a(integer      m,
               integer      n)
  { 
    if (m == 0) 
      return n + 1; 
    else 
      if (n == 0) 
        return a(m - 1,1); 
      else 
        return a(m - 1,a(m,n - 1)); 
  } 


main(int   argc,
     char  *argv[])
{ 
  printf("Ackerman function...\n"); 
  r = a(3,6); 
  printf("finished, R=%d\n",r); 
}



