
/*
 * Generated by TPTC - Translate Pascal to C
 *     Version 1.7 03/26/88   (C) 1988 S.H.Smith
 */
#include "tptcmac.h"

/*
 * Usage: DIAL xxx-xxxx
 */ 

 /* program dial  */ 
    /* dials number on command line to Hayes compatible modem on COM1 */ 


  #define com_base 0x3F8    /* Use 3F8 for COM1, 2F8 for COM2 */ 

    /* Offsets from Com_Base for async control ports              */ 
  #define rx   0    /* Receiver Buffer Register       */ 
  #define tx   0    /* Transmitter Buffer Register    */ 
  #define lc   3    /* Line Control Register          */ 
  #define mc   4    /* Modem Control Register         */ 
  #define ls   5    /* Line Status Register           */ 
  #define dll  0    /* Divisor Latch, Low Order Byte  */ 
  #define dlh  1    /* Divisor Latch, High Order Byte */ 

  #define no_parity 0x03  


   typedef char anystring[81]; 



void         send(char *       command)
{ 
   integer      p; 
   char         c; 
   integer      i; 



    /* send string to modem */ 
  for (p = 1; p <= strlen(command); p++) 
  { 
    c = command[p-1]; 
    outportb(com_base + tx,c);
    do { 
    }  while (!(inportb(com_base + ls) >= 0x20)); 
    p = succ(p); 

    i = 0; 
    do { 
      i = succ(i); 
    }  while (!(i >= 1000)); 
  } 
} 



main(int   argc,
     char  *argv[])
{ 
    /* init modem */ 
  outportb(com_base + lc,0x83);  /* Set baud rate, No parity, 8 bits */ 
  outportb(com_base + dll,96);  /* 1200 baud */ 
  outportb(com_base + dlh,0);
  outportb(com_base + lc,no_parity);
  outportb(com_base + mc,0x03);  /* Turn ON DTR and RTS */ 

    /* set up modem control string */ 
  send(scat("ATDT%s\r",paramstr(1))); 
}



