
/*
 * Generated by TPTC - Translate Pascal to C
 *     Version 1.7 03/26/88   (C) 1988 S.H.Smith
 */
#include "tptcmac.h"

/*
 * fmap - find symbols related to an address in a .MAP load
 *        map generated by LINK or TMAP
 *
 * S.H.Smith, 27-jan-86
 *
 */ 

/* G() */   
/* P() */   
/* C(OFF) */   


   #define version "FMAP 1.0 (1/26/87 SHS)"  


   typedef char anystring[81]; 


   anystring    line; 
   text         fd; 
   anystring    target; 
   anystring    mapname; 



void         abort_check(void)
{ 
   if (keypressed) 
   { 
      printf("aborted\n"); 
      exit(0);
   } 
} 



void         parse_segments(void)
{ 
   printf("Segments\n"); 
   do { 
      fscanv(fd,"#\n",line); 
   }  while (!(strlen(line) < 20)); 
} 



void         parse_by_name(void)
{ 
   printf("Names\n"); 
   fscanv(fd,"#\n",line); 

   do { 
      fscanv(fd,"#\n",line); 
      abort_check(); 
   }  while (!(strlen(line) < 17)); 
} 



void         parse_by_value(void)
{ 
   anystring    pr; 
   anystring    ad; 
   anystring    ppr; 
   anystring    pad; 
   anystring    pline; 


   printf("Values\n"); 
   fscanv(fd,"#\n",line); 
   strcpy(pad,"0000"); 
   strcpy(ppr,""); 

   do { 
      strcpy(ad,copy(line,7,4)); 
      strcpy(pr,copy(line,18,99)); 
      if ((strcmp(ppr,"") != 0) && (strcmp(target,pad) >= 0) && (strcmp(target,ad) < 0)) 
         printf("%s-%s %s\n",pad,ad,pline); 

      strcpy(pad,ad); 
      strcpy(ppr,pr); 
      strcpy(pline,line); 

      fscanv(fd,"#\n",line); 
      abort_check(); 
   }  while (!(strlen(line) < 17)); 
} 



void         output_lines(char *       name,
                          integer      first,
                          integer      last)
{ 
   text         fd; 
   integer      n; 
   anystring    b; 


   printf("Output lines %d-%d from %s\n",first,last,name); 
   assign(fd,name); 
/* I(OFF) */   
   reset(&fd); 
/* I(ON) */   
   if (ioresult != 0) 
   { 
      printf("can't find source file: %s\n",name); 
      printf("need lines %d-%d\n",first,last); 
      exit(0);
   } 

/* I(OFF) */   
   for (n = 1; n <= first - 1; n++) 
      fscanv(fd,"#\n",b); 

   for (n = first; n <= last + 1; n++) 
   { 
      printf("%6d| %s\n",n,b); 
      fscanv(fd,"#\n",b); 
      abort_check(); 
   } 
/* I(ON) */   

   fclose(fd); 
} 



   anystring    name; 
   integer      ln; 
   anystring    ad; 
   integer      pln; 
   anystring    pad; 
   boolean      first; 

   
void         check_match(void)
   { 
      printf("   check match, %s-%s  lines %d-%d\n",pad,ad,pln,ln); 

      if ((pln != 0) && (strcmp(target,pad) >= 0) && (strcmp(target,ad) < 0)) 
      { 
         if (first) 
         { 
            printf("\n"); 
            printf("==============================\n"); 
            printf("%s\n",name); 
            first = false; 
         } 

         if ((ln - pln) < 20) 
         { 
            printf("---------\n"); 
            printf("%s-%s\n",pad,ad); 
            output_lines(name,pln,ln); 
         } 
         else 
         { 
            printf("---------\n"); 
            printf("%s-%s  lines %d-%d\n",pad,ad,pln,ln); 
         } 
      } 
   } 


void         parse_line_numbers(void)
{ 
   integer      i; 
   integer      code; 
   anystring    buf; 


   printf("Line numbers: %s\n",line); 

   i = cpos('(',line) + 1; 
   strcpy(name,""); 
   while (line[i-1] != ')') 
   { 
      sbld(name,"%s%c",name,line[i-1]); 
      i = i + 1; 
   } 

   fscanv(fd,"#\n",line); 
   printf("name=[%s]\n",name); 

   pln = 0; 
   strcpy(pad,"0000"); 
   first = true; 

   do { 
      abort_check(); 

      while (strlen(line) > 6) 
      { 

           /* extract the line number */ 
         strcpy(buf,copy(line,1,5)); 
         while (strcmp(copy(buf,1,1)," ") == 0) 
            delete(buf,1,1); 
         val(buf,&ln,&code); 

           /* extract the code address */ 
         strcpy(ad,copy(line,12,4)); 

           /* remove the processed part of the line */ 
         delete(line,1,17); 

           /* if target is between two lines, then print it out */ 
         check_match(); 

         strcpy(pad,ad); 
         pln = ln; 
      } 

      fscanv(fd,"#\n",line); 
   }  while (!(strlen(line) < 6)); 

   check_match();   /* process the last line */ 
} 



void         parse_others(void)
{ 
   printf("Other: %s\n",line); 
   fscanv(fd,"#\n",line); 
} 



void         parse_mapfile(void)
{ 
   printf("Scanning mapfile %s\n",mapname); 
   printf("for address %s:\n",target); 
   printf("\n"); 

   fscanv(fd,"#\n",line); 

   while (!feof(fd)) 
   { 
      if (strcmp(copy(line,1,30)," Start  Stop   Length Name    ") == 0) 
         parse_segments(); 
      else 
      if (strcmp(copy(line,1,30),"  Address         Publics by N") == 0) 
         parse_by_name(); 
      else 
      if (strcmp(copy(line,1,30),"  Address         Publics by V") == 0) 
         parse_by_value(); 
      else 
      if (strcmp(copy(line,1,17),"Line numbers for ") == 0) 
         parse_line_numbers(); 
      else 
         parse_others(); 

      abort_check(); 
   } 

   fclose(fd); 
} 



   integer      i; 


main(int   argc,
     char  *argv[])
{ 
   printf("\n"); 
   printf("%s\n",version); 
   printf("\n"); 

   if (paramcount != 2) 
   { 
      printf("Usage: fmap MAPFILE TARGET_ADDRESS\n"); 
      printf("Finds references to TARGET_ADDRESS in MAPFILE.\n"); 
      exit(1);
   } 

   strcpy(mapname,paramstr(1)); 
   if (cpos('.',mapname) == 0) 
      sbld(mapname,"%s.MAP",mapname); 

   assign(fd,mapname); 
/* I(OFF) */   
   reset(&fd); 
/* I(ON) */   
   if (ioresult != 0) 
   { 
      printf("can't open mapfile: %s\n",mapname); 
      exit(0);
   } 

   strcpy(target,paramstr(2)); 
   for (i = 1; i <= strlen(target); i++) 
      target[i-1] = toupper(target[i-1]); 

   if (strlen(target) != 4) 
   { 
      printf("TARGET_ADDRESS must be 4 hex digits\n"); 
      exit(0);
   } 

   parse_mapfile(); 
   printf("\n"); 
}



