
/*
 * Generated by TPTC - Translate Pascal to C
 *     Version 1.7 03/26/88   (C) 1988 S.H.Smith
 */
#include "tptcmac.h"
/*
 * Examples of pointer manipulation
 *
 */ 

 /* program pointer_use_example  */ 


    typedef char name[21]; 


    name         *my_name; /* My_Name is a pointer to a string[20] */ 
    integer      *my_age; /* My_Age is a pointer to an integer */ 


main(int   argc,
     char  *argv[])
{ 
   my_name = malloc(sizeof(*my_name));
   my_age = malloc(sizeof(*my_age));

   strcpy(*my_name,"John Q Doe"); 
   *my_age = 27; 

   printf("My name is %s\n",*my_name); 
   printf("My age is %3d\n",*my_age); 

   dispose(my_name); 
   dispose(&my_age); 
}



