
/*
 * Generated by TPTC - Translate Pascal to C
 *     Version 1.7 03/26/88   (C) 1988 S.H.Smith
 */
#include "tptcmac.h"

/*
 * Non-recursive quick sort
 */ 

 /* program quicksort  */ 


  #define n    15000  
  #define stacksize 60  
  #define insertparam 20  

  typedef int  /* 0..15000 */ index; 

  index        l, r, i, j, m; 
  integer      v, t; 
  int          /* 0..60 */ s; 
  struct stack { 
                                  index        l, r; 
                                } stack[stacksize]; 
  integer      a[ /* index */ 15001]; 


main(int   argc,
     char  *argv[])
{   /*  qsort */ 
  printf("Non-recursive QuickSort...\n"); 
  for (i = 1; i <= n; i++) 
    a[i] = i % 500; 
  a[0] = -maxint; 
  s = 1; 
  stack[0].l = 1; 
  stack[0].r = n; 
  do { 
    l = stack[s-1].l; 
    r = stack[s-1].r; 
    s = s - 1; 
    while (r - l > insertparam) 
      { 
        m = (l + r) / 2; 
        t = a[m]; 
        a[m] = a[l + 1]; 
        a[l + 1] = t; 
        if (a[l + 1] > a[r]) 
          { 
            t = a[l + 1]; 
            a[l + 1] = a[r]; 
            a[r] = t; 
          } 
        if (a[l] > a[r]) 
          { 
            t = a[l]; 
            a[l] = a[r]; 
            a[r] = t; 
          } 
        if (a[l + 1] > a[l]) 
          { 
            t = a[l + 1]; 
            a[l + 1] = a[l]; 
            a[l] = t; 
          } 
        i = l + 1; 
        j = r; 
        v = a[l]; 
        do { 
          do { 
            i = i + 1; 
          }  while (!(a[i] >= v)); 
          do { 
            j = j - 1; 
          }  while (!(a[j] <= v)); 
          if (i < j) { 
            t = a[i]; 
            a[i] = a[j]; 
            a[j] = t; 
          } 
        }  while (!(i > j)); 
        a[l] = a[j]; 
        a[j] = v; 
        s = s + 1; 
        if (i - l < r - i) 
          { 
            stack[s-1].l = i; 
            stack[s-1].r = r; 
            r = j - 1; 
          } 
        else 
          { 
            stack[s-1].l = l; 
            stack[s-1].r = j - 1; 
            l = i; 
          } 
      } 
  }  while (!(s == 0)); 

  for (l = 1; l <= n - 1; l++) 
    { 
      if (a[l] > a[l + 1]) 
        { 
          v = a[l + 1]; 
          i = l; 
          do { 
            a[i + 1] = a[i]; 
            i = i - 1; 
          }  while (!(a[i] <= v)); 
          a[i + 1] = v; 
        } 
    } 

  printf("finished\n"); 
}



