
/*
 * Generated by TPTC - Translate Pascal to C
 *     Version 1.7 03/26/88   (C) 1988 S.H.Smith
 */
#include "tptcmac.h"

/*
 * Sieve of Eratosthenes
 */ 

 /* program sieve  */ 


  #define size 8190  

  boolean      flags[size+1]; 
  integer      prime, k, count; 
  integer      inter, i; 


main(int   argc,
     char  *argv[])
{ 
  printf("Sieve of Eratosthenes...\n"); 
  printf("50 iterations"); 
  printf("\n"); 
  for (inter = 1; inter <= 50; inter++) 
    { 
      count = 0; 
      for (i = 0; i <= size; i++) 
        flags[i] = true; 
      for (i = 0; i <= size; i++) 
        { 
          if ((flags[i])) 
            { 
              prime = i + i + 3; 
              k = i + prime; 
              while ((k <= size)) 
                { 
                  flags[k] = false; 
                  k = k + prime; 
                } 
              count = count + 1; 
            } 
        } 
    } 
  printf("%d primes\n",count); 
}



