
/*
 * Generated by TPTC - Translate Pascal to C
 *     Version 1.7 03/26/88   (C) 1988 S.H.Smith
 */
#include "tptcmac.h"

/*
 * Example of array subscripting
 */ 

 /* program a_small_record  */ 


     typedef struct description { 
       integer      year; 
       char         model[21]; 
       char         engine[9]; 
     } description; 


     description  cars[10]; 
     integer      index; 


main(int   argc,
     char  *argv[])
{ /* main program */ 
   for (index = 1; index <= 10; index++) { 
      cars[index-1].year = 1930 + index;   /* should be ...[index-1] */ 
      strcpy(cars[index-1].model,"Duesenburg"); 
      strcpy(cars[index-1].engine,"V8"); 
   } 

   strcpy(cars[1].model,"Stanley Steamer"); 
   strcpy(cars[1].engine,"Coal"); 
   strcpy(cars[6].engine,"V12"); 
   strcpy(cars[8].model,"Ford"); 
   strcpy(cars[8].engine,"rusted"); 

   for (index = 1; index <= 10; index++) { 
      printf("My %4d ",cars[index-1].year); 
      printf("%s has a ",cars[index-1].model); 
      printf("%s engine.\n",cars[index-1].engine); 
   } 
}



