
/*
 * Generated by TPTC - Translate Pascal to C
 *     Version 1.7 03/26/88   (C) 1988 S.H.Smith
 */
#include "tptcmac.h"

/*
 * Example of tpas4.0 WORD data type
 */ 

 /* program get_time_and_date  */ 

#include "dos.UNH"

/* TPTC: TIMEDAT4.PAS(8): Fatal: Can't open unit symbol file, tok=C:\INC\dos.UNS */


