//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by XTResource.rc
//
#define XT_IDB_SCROLL_ARW               4499
#define XT_IDB_FONTTYPE                 4500
#define XT_IDC_BEGINDRAG                4501
#define XT_IDS_NAME                     4502
#define XT_IDS_SIZE                     4503
#define XT_IDS_CONTRACT                 4504
#define XT_IDS_TYPE                     4505
#define XT_IDS_MODIFIED                 4506
#define XT_IDS_REGKEY                   4507
#define XT_IDS_INVALID_VER              4508
#define XT_IDS_WIN_PLACEMENT            4509
#define XT_IDS_COLOR_AUTO               4510
#define XT_IDS_COLOR_CUST               4511
#define XT_IDS_SECTION                  4512
#define XT_IDS_ENTRY                    4513
#define XT_IDS_SETTINGS                 4514
#define XT_IDS_SETTINGS_TBAR            4515
#define XT_IDS_SETTINGS_CBAR            4516
#define XT_IDS_WNDPOS                   4517
#define XT_IDC_DRAG                     4518
#define XT_IDS_DOCKWND                  4518
#define XT_IDS_RES_ASSERT               4519
#define XT_IDC_HAND                     4520
#define XT_IDS_TOOLBAR                  4520
#define XT_IDS_ERROR_BLANK              4521
#define XT_IDC_HSPLITBAR                4522
#define XT_IDS_STATUSBAR                4522
#define XT_IDS_ERROR_EXISTS             4523
#define XT_IDC_NODRAG                   4524
#define XT_IDS_ERROR_LIMIT              4525
#define XT_IDS_CUSTOM_BAR               4526
#define XT_IDC_VSPLITBAR                4527
#define XT_IDS_CUSTOM_CONFIRM           4528
#define XT_IDB_BTN_BAR                  4529
#define XT_IDC_NOHAND                   4530
#define XT_IDS_NOHELPTOPIC              4531
#define XT_IDB_BTN_OUT                  4532
#define XT_IDM_POPUP                    4533
#define XT_IDR_TBAR_HDR                 4534
#define XT_IDR_TBAR_OUT                 4535
#define XT_IDS_SE_0                     4536
#define XT_IDS_SE_ERR_FNF               4537
#define XT_IDS_SE_ERR_PNF               4538
#define XT_IDS_SE_ERR_ACCESSDENIED      4539
#define XT_IDS_SE_ERR_OOM               4540
#define XT_IDS_SE_ERR_BAD_FORMAT        4541
#define XT_IDS_SE_ERR_SHARE             4542
#define XT_IDS_SE_ERR_ASSOCINCOMPLETE   4543
#define XT_IDS_SE_ERR_DDETIMEOUT        4544
#define XT_IDS_SE_ERR_DDEFAIL           4545
#define XT_IDS_SE_ERR_DDEBUSY           4546
#define XT_IDS_SE_ERR_NOASSOC           4547
#define XT_IDS_SE_ERR_DLLNOTFOUND       4548
#define XT_IDS_SE_ERR_UNKOWN            4549
#define XT_XT_IDC_BTN_CAPT              4550
#define XT_IDS_CLR_BLACK                4551
#define XT_IDS_CLR_BROWN                4552
#define XT_IDS_CLR_OLIVE_GREEN          4553
#define XT_IDS_CLR_DARK_GREEN           4554
#define XT_IDS_CLR_DARK_TEAL            4555
#define XT_IDS_CLR_DARK_BLUE            4556
#define XT_IDS_CLR_INDIGO               4557
#define XT_IDS_CLR_GRAY80               4558
#define XT_IDS_CLR_DARK_RED             4559
#define XT_IDS_CLR_ORANGE               4560
#define XT_IDS_CLR_DARK_YELLOW          4561
#define XT_IDS_CLR_GREEN                4562
#define XT_IDS_CLR_TEAL                 4563
#define XT_IDS_CLR_BLUE                 4564
#define XT_IDS_CLR_BLUEGRAY             4565
#define XT_IDS_CLR_GRAY50               4566
#define XT_IDS_CLR_RED                  4567
#define XT_IDS_CLR_LIGHTORANGE          4568
#define XT_IDS_CLR_LIME                 4569
#define XT_IDS_CLR_SEA_GREEN            4570
#define XT_IDS_CLR_AQUA                 4571
#define XT_IDS_CLR_LIGHT_BLUE           4572
#define XT_IDS_CLR_VIOLET               4573
#define XT_IDS_CLR_GRAY40               4574
#define XT_IDS_CLR_PINK                 4575
#define XT_IDS_CLR_GOLD                 4576
#define XT_IDS_CLR_YELLOW               4577
#define XT_IDS_CLR_BRIGHT_GREEN         4578
#define XT_IDS_CLR_TURQUOISE            4579
#define XT_IDS_CLR_SKY_BLUE             4580
#define XT_IDS_CLR_PLUM                 4581
#define XT_IDS_CLR_GRAY25               4582
#define XT_IDS_CLR_ROSE                 4583
#define XT_IDS_CLR_TAN                  4584
#define XT_IDS_CLR_LIGHT_YELLOW         4585
#define XT_IDS_CLR_LIGHT_GREEN          4586
#define XT_IDS_CLR_LIGHT_TURQUOISE      4587
#define XT_IDS_CLR_PALE_BLUE            4588
#define XT_IDS_CLR_LAVENDER             4589
#define XT_IDS_CLR_WHITE                4590
#define XT_IDS_CLR_GRAY                 4591
#define XT_IDS_CLR_MAROON               4592
#define XT_IDS_CLR_OLIVE                4593
#define XT_IDS_CLR_NAVY                 4594
#define XT_IDS_CLR_PURPLE               4595
#define XT_IDS_CLR_SILVER               4596
#define XT_IDS_CLR_FUCHSIA              4597
#define XT_IDS_CLR_NOFILL               4598
#define XT_IDS_CLR_NOFILL_TIP           4599
#define XT_IDS_AUTOMATIC                4600
#define XT_IDS_AUTOMATIC_TIP            4601
#define XT_IDS_MORE_COLORS              4602
#define XT_IDS_MORE_COLORS_TIP          4603
#define XT_IDS_STD_COLORS               4604
#define XT_IDB_LIGHTBULB                4605
#define XT_IDD_TIPOFTHEDAY              4606
#define XT_IDS_DIDYOUKNOW               4607
#define XT_IDS_FILE_ABSENT              4608
#define XT_IDS_FILE_CORRUPT             4609
#define XT_IDI_XTREME                   4610
#define XT_IDB_LISTEDIT                 4611
#define XT_IDS_CUSTSHEET_CAPTION        4612
#define XT_IDD_CUSTPAGE1                4613
#define XT_IDD_CUSTPAGE2                4614
#define XT_IDD_CUSTPAGE3                4615
#define XT_IDD_NEWTOOLBAR               4616
#define XT_IDR_BLANK_TOOLBAR            4617
#define XT_IDD_PREVIEW_TOOLBAR          4618
#define XT_IDB_BTN_PRINT                4619
#define XT_IDC_TABCTRL                  5500
#define XT_IDC_GROUP_EDIT               5501
#define XT_IDC_EDIT_TOOLBAR             5502
#define XT_IDC_LBOX_EDIT                5503
#define XT_IDC_LBOX_CHECK               5504
#define XT_IDC_LBOX_CATEGORIES          5505
#define XT_IDC_LBOX_COMMANDS            5506
#define XT_IDC_TXT_TOOLBARS             5507
#define XT_IDC_TXT_CATEGORIES           5508
#define XT_IDC_TXT_COMMANDS             5509
#define XT_IDC_TXT_SELECTED             5510
#define XT_IDS_BTN_CLOSE                5511
#define XT_IDC_BTN_CLOSE                5511
#define XT_IDS_BTN_EXPAND               5512
#define XT_IDC_BTN_EXPAND               5512
#define XT_IDC_BTN_LEFT                 5513
#define XT_IDC_BTN_RIGHT                5514
#define XT_IDC_BTN_HOME                 5515
#define XT_IDC_BTN_END                  5516
#define XT_IDS_BTN_NEW                  5517
#define XT_IDC_BTN_NEW                  5517
#define XT_IDS_BTN_DELETE               5518
#define XT_IDC_BTN_DELETE               5518
#define XT_IDS_BTN_UP                   5519
#define XT_IDC_BTN_UP                   5519
#define XT_IDS_BTN_DOWN                 5520
#define XT_IDC_BTN_DOWN                 5520
#define XT_IDC_BTN_BROWSE               5521
#define XT_IDC_BTN_DAYTIP_BORDER        5522
#define XT_IDC_CHK_DAYTIP_SHOW          5523
#define XT_IDC_BTN_DAYTIP_NEXT          5524
#define XT_IDC_BTN_RENAME               5525
#define XT_IDC_BTN_RESET                5526
#define XT_IDC_BTN_DESCRIPTION          5527
#define XT_IDC_CHK_STANDARD             5528
#define XT_IDC_CHK_RECIENTMENU          5529
#define XT_IDC_CHK_SHOWFULL             5530
#define XT_IDC_LARGEICON                52771
#define XT_IDC_SMALLICON                52772
#define XT_IDC_SORTASC                  52773
#define XT_IDC_SORTDSC                  52774
#define XT_IDC_ALIGNLEFT                52775
#define XT_IDC_ALIGNRIGHT               52776
#define XT_IDC_ALIGNCENTER              52777
#define XT_IDC_REMOVEITEM               52778
#define XT_IDC_RENAMEITEM               52779
#define XT_IDC_CUSTOMIZE                52780
#define XT_IDS_DIRECTORIES              52781
#define XT_IDS_FILES                    52782
#define XT_IDC_BLANK                    52783
#define XT_IDC_REMOVEGROUP              52784
#define XT_IDC_RENAMEGROUP              52785

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        4620
#define _APS_NEXT_COMMAND_VALUE         52786
#define _APS_NEXT_CONTROL_VALUE         5531
#define _APS_NEXT_SYMED_VALUE           4501
#endif
#endif
