<HTML>
<HEAD>
	<TITLE><!--#include file="version.inc"--></TITLE>

</HEAD>

<!--
	RISKYCHAT LIVES IN AN ASP ENVIRONMENT
	IT'S COOL AND I HOPE YOU'LL LIKE IT
	RISKYCHAT HAS BEEN WRITTEN BY filippo de vita - wave@flashnet.it
	HE SHOULD BE SURFING WHEN YOU READ THIS
-->

<%
	
	If Application("Status") = 1 Then
		Session("nome_utente") = ""
		%>
		
		<FRAMESET FRAMEBORDER=no BORDER=0 COLS="630,*,20" FRAMESPACING=0>
			<FRAMESET FRAMEBORDER=no BORDER=0 ROWS="50,*,98" framespacing=0>
				<FRAME MARGINHEIGHT=0 MARGINWIDTH=00 SRC="big_top.asp" NAME="big_top" NORESIZE FRAMEBORDER=no BORDER=0 SCROLLING=no>
				<FRAMESET FRAMEBORDER=no BORDER=0 COLS="147,483" framespacing=0>
					<FRAME MARGINHEIGHT=0 MARGINWIDTH=10 SRC="users.asp" NAME="users" NORESIZE FRAMEBORDER=no BORDER=0>
					<FRAMESET FRAMEBORDER=no BORDER=0 ROWS="21,*,8" framespacing=0>
						<FRAME MARGINHEIGHT=0 MARGINWIDTH=10 SRC="top.asp" NAME="top" NORESIZE FRAMEBORDER=no BORDER=0 SCROLLING=no>
						<FRAMESET FRAMEBORDER=no BORDER=0 COLS="17,451,15" framespacing=0>
							<FRAME MARGINHEIGHT=0 MARGINWIDTH=10 SRC="sx.asp" NAME="sx" NORESIZE FRAMEBORDER=no BORDER=0 SCROLLING=no>
							<FRAME MARGINHEIGHT=0 MARGINWIDTH=10 SRC="left.asp" NAME="left" NORESIZE FRAMEBORDER=no BORDER=0>
							<FRAME MARGINHEIGHT=0 MARGINWIDTH=10 SRC="dx.asp" NAME="dx" NORESIZE FRAMEBORDER=no BORDER=0 SCROLLING=no>
						</FRAMESET>	
						<FRAME MARGINHEIGHT=0 MARGINWIDTH=10 SRC="bottom.asp" NAME="bottom" NORESIZE FRAMEBORDER=no BORDER=0 SCROLLING=no>
					</FRAMESET>
				</FRAMESET>
				<FRAME MARGINHEIGHT=0 MARGINWIDTH=10 SRC="right.asp" NAME="right" NORESIZE FRAMEBORDER=no BORDER=0>
			</FRAMESET>
			<FRAME MARGINHEIGHT=0 MARGINWIDTH=0 SRC="destra.htm" NAME="destra" NORESIZE FRAMEBORDER=no BORDER=0 SCROLLING=no>
			<FRAME MARGINHEIGHT=0 MARGINWIDTH=0 SRC="zero.asp" NAME="zero" NORESIZE FRAMEBORDER=no BORDER=0 SCROLLING=no>
		</FRAMESET>
		<%
	Else
		%>
		chat non startata...<A HREF="start.asp" TARGET="_new">clicca qui</A>  per startare
		<%
	End If
%>

</HTML>