
/*
 * Generated by TPTC - Translate Pascal to C
 *     Version 1.7 03/26/88   (C) 1988 S.H.Smith
 */
#include "tptcmac.h"

/*
 * Example of sets of characters
 *
 */ 

 /* program find_all_lower_case_characters  */ 


    #define string_size 30  


    typedef setrec /* setof('a',__,'z',_E) */ low_set; 


    low_set      data_set; 
    char         storage[string_size+1]; 
    int          /* 1..30 */ index; 
    char         print_group[27]; 


main(int   argc,
     char  *argv[])
{ /* main program */ 
   data_set = setof(_E); 
   strcpy(print_group,""); 
   strcpy(storage,"This is a set test."); 

   for (index = 1; index <= strlen(storage); index++) { 
      if (inset(storage[index-1],setof('a',__,'z',_E))) { 
         if (inset(storage[index-1],data_set)) 
            printf("%4d   %c is already in the set\n",index,storage[index-1]); 
         else { 
            data_set = data_set + setof(storage[index-1],_E); 
            sbld(print_group,"%s%c",print_group,storage[index-1]); 
            printf("%4d   %c added to group, complete group = %s\n",index,storage[index-1],print_group); 
         } 
      } 
      else 
         printf("%4d   %c is not a lower case letter\n",index,storage[index-1]); 
   } 
}



