
/*
 * Generated by TPTC - Translate Pascal to C
 *     Version 1.7 03/26/88   (C) 1988 S.H.Smith
 */
#include "tptcmac.h"

/*
 * Example of pointer manipulation with circular type declarations
 *
 */ 

 /* program linked_list_example  */ 


     #define next_pointer struct full_name * 

     typedef struct full_name { 
       char         first_name[13]; 
       char         initial; 
       char         last_name[16]; 
       next_pointer next; 
     } full_name;
     #undef next_pointer
     typedef struct full_name *next_pointer; 


     next_pointer start_of_list; 
     next_pointer place_in_list; 
     next_pointer temp_place; 
     integer      index; 


main(int   argc,
     char  *argv[])
{ /* main program */ 
                       /* generate the first name in the list */ 
   place_in_list = malloc(sizeof(*place_in_list));
   start_of_list = place_in_list; 
   strcpy(place_in_list->first_name,"John"); 
   place_in_list->initial = 'Q'; 
   strcpy(place_in_list->last_name,"Doe"); 
   place_in_list->next = nil; 
                       /* generate another name in the list */ 
   temp_place = place_in_list; 
   place_in_list = malloc(sizeof(*place_in_list));
   temp_place->next = place_in_list; 
   strcpy(place_in_list->first_name,"Mary"); 
   place_in_list->initial = 'R'; 
   strcpy(place_in_list->last_name,"Johnson"); 
   place_in_list->next = nil; 
                  /* add 10 more names to complete the list */ 
   for (index = 1; index <= 10; index++) { 
      temp_place = place_in_list; 
      place_in_list = malloc(sizeof(*place_in_list));
      temp_place->next = place_in_list; 
      strcpy(place_in_list->first_name,"William"); 
      place_in_list->initial = 'S'; 
      strcpy(place_in_list->last_name,"Jones"); 
      place_in_list->next = nil; 
   } 
                   /* display the list on the video monitor */ 
   place_in_list = start_of_list; 
   do { 
      printf("%s",place_in_list->first_name); 
      printf(" %c",place_in_list->initial); 
      printf(" %s\n",place_in_list->last_name); 
      temp_place = place_in_list; 
      place_in_list = place_in_list->next; 
   }  while (!(temp_place->next == nil)); 
}



