
/*
 * Generated by TPTC - Translate Pascal to C
 *     Version 1.7 03/26/88   (C) 1988 S.H.Smith
 */
#include "tptcmac.h"

/*
 * MiniCrt - simplified version of Borland's CRT unit.
 * Does not EVER do direct video.  The standard crt unit
 * locks up multi-taskers with its direct video checking before
 * the user program can turn it off.
 *
 * Samuel H. Smith, 20-dec-87
 *
 */ 

   
/* TPTC: MINICRT.PAS(12): Warning: Missing include file, tok=PRODEF.INC */


 /* unit minicrt  */ 



   
      #include "dos.UNH"
      
/* TPTC: MINICRT.PAS(19): Fatal: Can't open unit symbol file, tok=C:\INC\dos.UNS */
      

