
/*
 * Generated by TPTC - Translate Pascal to C
 *     Version 1.7 03/26/88   (C) 1988 S.H.Smith
 */
#include "tptcmac.h"

/*
 * Example of PASCAL/MT+
 */ 

 /* module menus  */ 


   
/* TPTC: MTPLUS.PAS(9): Warning: Missing include file, tok=MENUS.CON */



    boolean      dummy_b; 
    char         date[13]; 
    byte         revs; 
    longint      wait_period; 
    char         s[STRSIZ];   /* default length? */ 
    extern boolean in_top_level; 
    extern char  mns[200][41]; 
    extern byte  l_margin; 

    /*------- notice the external declaration -------*/ 

    
extern void  putchrs();

extern char  wait_for_char();

extern char  get_chr_and_messages();

extern longint sys_tick();

extern void  answer();
/*------- notice the external declaration in an overlay #1 -------*/ 
/* overlay 1 */ 
extern void  edit();
/* overlay 2 */ 
extern void  prepare();
/* overlay 2 */ 
extern void  save_sys_parms();
/* overlay 5 */ 
extern void  load_msg();
/* overlay 5 */ 
extern void  save_msg();
/* overlay 5 */ 
extern void  kill_msg();
/* overlay 5 */ 
extern void  view_msg();

void         set_date(char *       s)
{ 
  strcpy(date,s); 
  strcpy(attr,hilt); 
  xygoto(60,1); 
  iprintf(put_chr,"%s",date); 
  strcpy(attr,normal); 
} 


void         switch(char         ch)
{ 
  sbld(c,"%d",(c & 0xFF00) | ord(ch)); 
  /*----           ^ this is a bit-wise OR ----*/ 
  /*----  ^ this is a bit-wise AND ----*/ 
} 

/* E(OFF) */   
/* E(ON) */   



