
/*
 * Generated by TPTC - Translate Pascal to C
 *     Version 1.7 03/26/88   (C) 1988 S.H.Smith
 */
#include "tptcmac.h"

/*
 * Another example of pointer manipulation
 *
 */ 


    typedef integer *int_point; 


    integer      index; 
    integer      *where; 
    integer      *who; 
    int_point    pt1, pt2, pt3; 


main(int   argc,
     char  *argv[])
{ 
   index = 17; 
   where = &index; 
   who = &index; 
   printf("The values are   %5d%5d%5d\n",index,*where,*who); 

   *where = 23; 
   printf("The values are   %5d%5d%5d\n",index,*where,*who); 

   pt1 = &index; 
   pt2 = pt1; 
   pt3 = pt2; 
   *pt2 = 151; 
   printf("The Pt values are%5d%5d%5d\n",*pt1,*pt2,*pt3); 
}



