
/*
 * Generated by TPTC - Translate Pascal to C
 *     Version 1.7 03/26/88   (C) 1988 S.H.Smith
 */
#include "tptcmac.h"

/*
 * Examples of set manipulation
 *
 */ 

 /* program define_some_sets  */ 


    typedef enum {  ice_cream,whipped_cream,banana,nuts,cherry,
                choc_syrup,strawberries,caramel,soda_water,
                salt,pepper,cone,straw,spoon,stick } goodies; 

     typedef setrec /* goodies */ treat; 


     treat        sundae; 
     treat        banana_split; 
     treat        soda; 
     treat        ice_cream_cone; 
     treat        nutty_buddy; 
     treat        mixed; 
     byte         index; 


main(int   argc,
     char  *argv[])
{ 
                /* define all ingredients used in each treat */ 
   ice_cream_cone = setof(ice_cream,cone,_E); 
   soda = setof(straw,soda_water,ice_cream,cherry,_E); 
   banana_split = setof(ice_cream,__,caramel,_E); 
   banana_split = banana_split + setof(spoon,_E); 
   nutty_buddy = setof(cone,ice_cream,choc_syrup,nuts,_E); 
   sundae = setof(ice_cream,whipped_cream,nuts,cherry,choc_syrup,spoon,_E); 

                 /* combine for a list of all ingredients used */ 

   mixed = ice_cream_cone + soda + banana_split + nutty_buddy + sundae; 
   mixed = setof(ice_cream,__,stick,_E) - mixed; /* all ingredients not used */ 

   if (inset(ice_cream,mixed)) printf("Ice cream not used\n"); 
   if (inset(whipped_cream,mixed)) printf("Whipped cream not used\n"); 
   if (inset(banana,mixed)) printf("Bananas not used\n"); 
   if (inset(nuts,mixed)) printf("Nuts are not used\n"); 
   if (inset(cherry,mixed)) printf("Cherrys not used\n"); 
   if (inset(choc_syrup,mixed)) printf("Chocolate syrup not used\n"); 
   if (inset(strawberries,mixed)) printf("Strawberries not used\n"); 
   if (inset(caramel,mixed)) printf("Caramel is not used\n"); 
   if (inset(soda_water,mixed)) printf("Soda water is not used\n"); 
   if (inset(salt,mixed)) printf("Salt not used\n"); 
   if (inset(pepper,mixed)) printf("Pepper not used\n"); 
   if (inset(cone,mixed)) printf("Cone not used\n"); 
   if (inset(straw,mixed)) printf("Straw not used\n"); 
   if (inset(spoon,mixed)) printf("Spoon not used\n"); 
   if (inset(stick,mixed)) printf("Stick not used\n"); 
}



