
/*
 * Generated by TPTC - Translate Pascal to C
 *     Version 1.7 03/26/88   (C) 1988 S.H.Smith
 */
#include "tptcmac.h"

/*
 * Example of character and enumeration subrange types
 */ 

 /* program scaler_operations  */ 


     typedef enum {  mon,tue,wed,thu,fri,sat,sun } days; 
     typedef int  /* mon..mon */ work; 
     typedef int  /* sat..sat */ rest; 


     days         day; /* This is any day of the week */ 
     work         workday; /* These are the the working days */ 
     rest         weekend; /* The two weekend days only */ 
     int          /* 1..12 */ index; 
     char         /* 'a'..'z' */ alphabet; 
     char         /* 'a'..'e' */ start; 


main(int   argc,
     char  *argv[])
{ /* main program */ 
   workday = tue; 
   weekend = sat; 
   day = workday; 
   day = weekend; 
   index = 3 + 2 * 2; 
   start = 'd'; 
   alphabet = start; 
                             /* since Alphabet is "d"    */ 
   start = succ(alphabet); /* Start will be 'e'        */ 
   start = pred(alphabet); /* Start will be 'c'        */ 
   day = wed; 
   day = succ(day); /* Day will now be 'Thu' */ 
   day = succ(day); /* Day will now be 'Fri' */ 
   index = ord(day); /* Index will be 4 (Fri = 4) */ 
}



