
/*
 * Generated by TPTC - Translate Pascal to C
 *     Version 1.7 03/26/88   (C) 1988 S.H.Smith
 */
#include "tptcmac.h"

 /* program test  */ 

  /* test source for tptc's translation of declarations */ 

  
    typedef struct compdatarec { 
                    byte         opr;   /*  Operator  */ 
                    integer t;  /* Selector */
                      union { 
                       struct {  integer      dat1, dat2;  } s0;
                       struct {  byte         str1, str2;  } s1;
                       struct {  byte         byt1, byt2;  } s2;
                       struct {  integer      int1, int2;  } s3;
                       struct {  real         real1, real2;  } s4;
                       struct {  boolean      bool1, bool2;  } s6;
                   } v;
                  } compdatarec; 

    typedef struct daterec { 
                integer      year; 
                integer      month; 
                integer      day; 
              } daterec; 

    typedef struct bufftyp { 
                integer      status; 
                integer      name1; 
                integer      name2; 
                boolean      name3; 
                integer      name4; 
                real         name5; 
                real         name6; 
                integer      name7[3]; 
                daterec      birth; 
                daterec      lastin; 
                daterec      recall; 
              } bufftyp; 


  
void         clearbuff(bufftyp *    buff,
                       integer      recn)
    { 
      bufftyp      blankbuf 
       = {0,
      0,
      0,
      false,
      0,
      0.0,
      0.0,
      {1, 0, 0},
      {0,0,0},
      {0,0,0},
      {0,0,0}}; 
    
        /* body of clearbuff */ 
      *buff = blankbuf; 
    } 

  

main(int   argc,
     char  *argv[])
{ 
      /* main block */ 
  }



