
/*
 * Generated by TPTC - Translate Pascal to C
 *     Version 1.7 03/26/88   (C) 1988 S.H.Smith
 */
#include "tptcmac.h"

/*
 * Examples of variant record types
 */ 

 /* program variant_record_example  */ 


     typedef enum {  car,truck,bicycle,boat } kind_of_vehicle; 

     typedef struct vehicle { 
       char         owner_name[26]; 
       integer      gross_weight; 
       real         value; 
       kind_of_vehicle what_kind;  /* Selector */
         union { 
          struct {  integer      wheels; 
                    char         engine[9];  } scar;
          struct {  char         motor[9]; 
                    integer      tires; 
                    integer      payload;  } struck;
          struct {  integer      tyres;  } sbicycle;
          struct {  byte         prop_blades; 
                    boolean      sail; 
                    char         power[9];  } sboat;
        } v;
       } vehicle; /* of record */ 


    vehicle      sunfish, ford, schwinn, mac; 


main(int   argc,
     char  *argv[])
{ /* main program */ 
   strcpy(ford.owner_name,"Walter"); /* fields defined in order */ 
   ford.gross_weight = 5750; 
   ford.value = 2595.00; 
   ford.what_kind = truck; 
   strcpy(ford.v.struck.motor,"V8"); 
   ford.v.struck.tires = 18; 
   ford.v.struck.payload = 12000; 

   { void *with1 = &sunfish; 
      what_kind = boat; /* fields defined in random order */ 
      with1->v.sboat.sail = true; 
      with1->v.sboat.prop_blades = 3; 
      strcpy(with1->v.sboat.power,"wind"); 
      with1->gross_weight = 375; 
      with1->value = 1300.00; 
      strcpy(with1->owner_name,"Herman and George"); 
      } 
   

   strcpy(ford.v.scar.engine,"flathead"); /* tag-field not defined yet but it */ 
   ford.what_kind = car; /* must be before it can be used    */ 
   ford.v.scar.wheels = 4; 
      /* notice that the non variant part is not redefined here */ 

   mac = sunfish; /* entire record copied, including the tag-field */ 

   if (ford.what_kind == car) /* this should print */ 
      printf("%s owns the car with a %s engine\n",ford.owner_name,ford.v.scar.engine); 

   if (sunfish.what_kind == bicycle) /* this should not print */ 
      printf("The sunfish is a bicycle which it shouldn't be\n"); 

   if (mac.what_kind == boat) /* this should print */ 
      printf("The mac is now a boat with%2d propeller blades.\n",mac.v.sboat.prop_blades); 
}



